### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by finferno00** [jazir555/GamesDows#10]
Whenever opening the Disable GamesDows, nothing shows up. Running as admin same thing. The Enable file works just fine. I am also unable to press the windows button, or access anything really outside of steam, it is just a black screen once steam is closed.

**Comment by jazir555** [comment]
>Whenever opening the Disable GamesDows, nothing shows up. Running as admin same thing. The Enable file works just fine. I am also unable to press the windows button, or access anything really outside of steam, it is just a black screen once steam is closed.

Please download this file and run it as admin:

https://github.com/jazir555/GamesDows/blob/main/Set%20explorer%20as%20shell.reg

This will reset explorer.exe to the shell. Please make sure to launch task scheduler and remove the scheduled tasks that are created by the enable script. I'll try to fix the disable script, thank you for reporting this.

**Comment by jazir555** [comment]
I have created a V2 of the disable script, could you please try it and let me know if it resolves your issue?

**Comment by finferno00** [comment]
I did manage to uninstall the script with the new copy, I had to run it through cmd instead of double clicking it. Thank you!

For anyone stuck like me, 
Ctrl + alt + del 
Open task manager
Run new task
just type "."
Run new task
cmd (make sure it is checked as admin) 
in cmd type "start C:\your path to the uninstall file"
Enter

**Comment by jazir555** [comment]
These scripts are meant to be run as administrator. If you were just double clicking the file it didn't have admin permissions.
