### ISSUE TITLE
Problems with accessing the desktop

### ISSUE THREAD

**Issue by Rizhikk** [jazir555/GamesDows#16]
Hello! Could you explain how to log in to the desktop after startup? Everything works and Playnite runs like it's a shell. Thank you so much for this opportunity! But I do not know how to return to the desktop because the buttons on the keyboard do not respond to the appearance of the command prompt or explorer, and the desktop itself replaces the gray screen. Thank you in advance!

**Comment by jazir555** [comment]
> Hello! Could you explain how to log in to the desktop after startup? Everything works and Playnite runs like it's a shell. Thank you so much for this opportunity! But I do not know how to return to the desktop because the buttons on the keyboard do not respond to the appearance of the command prompt or explorer, and the desktop itself replaces the gray screen. Thank you in advance!

Explorer (the desktop) launches in the background after a delay. There should be no command prompt window, that should be suppressed by the VBS script the batch script creates.

>and the desktop itself replaces the gray screen.

Can you please clarify this? I'm not sure I understand what you mean.

>But I do not know how to return to the desktop because the buttons on the keyboard do not respond to the appearance of the command prompt or explorer

You should be able to exit to Desktop from Playnite through the menu as you would normally.

**Comment by jazir555** [comment]
I've reverted the playnite script to the previous version, can you please download the new zip in the releases section and let me know if that resolves your issue?

**Comment by Rizhikk** [comment]
I managed to return to the desktop via manual startup in the task manager:)  If you mean that the desktop should appear after exiting Playnite, then no, it does not appear..

**Comment by jazir555** [comment]
> I managed to return to the desktop via manual startup in the task manager:) If you mean that the desktop should appear after exiting Playnite, then no, it does not appear..

That was absolutely an issue with the newer script, I've reverted to the old one. This version will solve your issue.

**Comment by Rizhikk** [comment]
Now I'll try and write to you!)  So just when you exit Playnite, the desktop will appear if everything is fixed?

**Comment by jazir555** [comment]
> Now I'll try and write to you!) So just when you exit Playnite, the desktop will appear if everything is fixed?

Yep!

**Comment by Rizhikk** [comment]
I tried the version that you just updated and now the problem is that Playnite does not start itself (that is, when rebooting, the script seems to work (the Windows bootloader and the logo itself are missing), then a gray screen appears and after a while the desktop Explorer itself appears (that is, Playnite does not start at all)

**Comment by jazir555** [comment]
> I tried the version that you just updated and now the problem is that Playnite does not start itself (that is, when rebooting, the script seems to work (the Windows bootloader and the logo itself are missing), then a gray screen appears and after a while the desktop Explorer itself appears (that is, Playnite does not start at all) Is there any way to completely reset all the settings of the current script configuration in order to try starting the script from scratch?

Yes, please run the uninstall script, then rerun the version you just downloaded.

**Comment by jazir555** [comment]
> I tried the version that you just updated and now the problem is that Playnite does not start itself (that is, when rebooting, the script seems to work (the Windows bootloader and the logo itself are missing), then a gray screen appears and after a while the desktop Explorer itself appears (that is, Playnite does not start at all) Is there any way to completely reset all the settings of the current script configuration in order to try starting the script from scratch?

I'm confused by what you mean here since the script only takes effect upon rebooting after running it, and then it will function exactly the same way on subsequent reboots.

**Comment by jazir555** [comment]
Nope still my fault, patched it again. Mb.

https://github.com/jazir555/GamesDows/releases/tag/v5

I'm reaching into the commit history to pull the file, I pulled the wrong one :/

**Comment by Rizhikk** [comment]
Playnite starts up again, but when exiting, the gray screen also appears (that is, the desktop does not appear.. Also now I do not know how to return to the desktop (running in task manager) does not return the desktop..

**Comment by Rizhikk** [comment]
Could you please give me the original version again as it worked well! And it allowed you to return to the desktop through a manual start of the process. explorer.exe in the Task Manager..

**Comment by jazir555** [comment]
For now start it in task manager twice. If you click on the commit history, download the most recent version from yesterday or the day before (whenever it was edited). 

I'm going to dinner right now, but I'll take another look and fix it when I get back!

**Comment by Rizhikk** [comment]
I tried the previous version and still have the same problem (i.e. on manual startup explorer.exe Explorer opens in the Task Manager, but not the desktop. I do not know what to do(

**Comment by jazir555** [comment]
> I tried the previous version and still have the same problem (i.e. on manual startup explorer.exe Explorer opens in the Task Manager, but not the desktop. I do not know what to do(

Explorer needs to be set as the shell before it's launched for the desktop to appear. What you can do is run the reg key included in the zip, then launch explorer in task manager.

**Comment by Rizhikk** [comment]
I also tried it, and when I run reg, an error appears.

**Comment by jazir555** [comment]
🤦

Run "regedit" in taskmanager

Navigating to the Key: Navigate to the following registry path: HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Winlogon 
Modifying the "Shell" Value:
On the right side of the registry window, locate the "Shell" key. 
Double-click on "Shell" to edit its value. 
Ensure the value is set to "explorer.exe". 
Click "OK" to save the change.

**Comment by jazir555** [comment]
Wait did you run the reg key as admin?

**Comment by Rizhikk** [comment]
Yes, of course. I was running as an administrator.. But the error still appears. I still can't get back to the desktop (But I changed to explorer.exe in the shell, as you indicated, it still didn't help (the reg file still gives an error

**Comment by jazir555** [comment]
You have to set it as the shell first, then launch explorer.exe in task manager.

**Comment by jazir555** [comment]
That's actually how the script starts explorer in the background, it resets the shell to explorer and then launches it.

**Comment by Rizhikk** [comment]
The command line itself does not appear when running bat scripts.

**Comment by jazir555** [comment]
Are you able to get into the desktop now? I'm going to get rid of the reg key file and just make it a bat file when I get back.

**Comment by Rizhikk** [comment]
I still can't access the desktop (Manual startup explorer.exe it starts the explorer, but not the desktop (that is, the screen is also completely missing, only the explorer (I tried changing the value in the Shell registry editor to explorer.exe .. It also didn't help;(

**Comment by jazir555** [comment]
Try setting it to the full explorer path in the registry then launch it in task manager:

C:\Windows\explorer.exe

**Comment by jazir555** [comment]
You can also just run the uninstall script and reboot

**Comment by Rizhikk** [comment]
The whole situation is the same.. Is it possible to completely delete and reset the entire configuration? I also want to note that now the command line does not open at all when launching bat files in the unpacked archive..

**Comment by jazir555** [comment]
Yes, running the disable games does script resets everything to normal

**Comment by Rizhikk** [comment]
And what should I do now?(

**Comment by jazir555** [comment]
Reboot, and the desktop should launch normally, playnite won't be set as the shell at all

**Comment by jazir555** [comment]
That should fix that issue and then I will patch the playnite variant when I get home.

**Comment by Rizhikk** [comment]
Unfortunately, I can't even take a screenshot because the related functions don't work due to the lack of a desktop (I tried to reboot, but the screen is still gray (explorer opens immediately, but not the taskbar, not the desktop, nothing else:(

**Comment by jazir555** [comment]
So the disable script isn't fixing this either?

If you reset explorer to the shell and open task scheduler and delete the scheduled task, you should be able to reboot and it should being the desktop back.

**Comment by Rizhikk** [comment]
Could you please explain in more detail how to do this? I kind of did this, but it also didn't bring back the desktop after restarting.

**Comment by jazir555** [comment]
I'm at dinner now, I'll have to get back to you when I get home.

**Comment by Rizhikk** [comment]
The entire configuration reset is required here, but unfortunately it is not provided. Since if there was such an opportunity, this problem would be solved very easily..(

**Comment by Rizhikk** [comment]
I don't know how, but I think I could do it) Anyway now Playnite runs as a shell as before but manually running explorer.exe now it returns the desktop again;) I think if we change the process now to explorer.exe then the desktop will open

**Comment by jazir555** [comment]
> The entire configuration reset is required here, but unfortunately it is not provided. Since if there was such an opportunity, this problem would be solved very easily..( I also checked the sfc/scannow and it did not reveal any violations.

The reset is the disable gamesdows script

**Comment by jazir555** [comment]
Let me know if the disable script works for you, from what others have reported it works as intended and reverts the setup to how Windows normally functions

**Comment by jazir555** [comment]
I updated the disable script btw, somehow it was missing commands for the playnite variant, give it the new one a shot and let me know
