### ISSUE TITLE
Steam Script doesn't execute properly

### ISSUE THREAD

**Issue by RedZombieHD** [jazir555/GamesDows#17]
When executing the script, it finishes making the manifest then exits the script. Its the v5 version, python is installed.
I've included a video and screenshot of the command prompt

![PXL_20241227_193159499_exported_2634](https://github.com/user-attachments/assets/2784332e-f070-4458-8801-ae7ce0fff6c8)

https://github.com/user-attachments/assets/40305443-ec4b-42e9-893b-56b75b2cf105

**Comment by RedZombieHD** [comment]
Executing it in an already opened cmd(admin) window shows the error

![PXL_20241227_202644517](https://github.com/user-attachments/assets/c199f0d1-5675-4518-abd0-1e9778e52581)

**Comment by jazir555** [comment]
Could you give this version a shot?

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Enable%20GamesDows%20Steam%20V4%20testing.bat

**Comment by RedZombieHD** [comment]
Looks like it doesn't create the vbs file
![PXL_20241228_090352979](https://github.com/user-attachments/assets/785563b7-8e18-4dd8-8d0c-81a4d7bd0c96)
![PXL_20241228_090208498](https://github.com/user-attachments/assets/eca438cd-1415-4f4f-983e-7517d59c5d79)

**Comment by jazir555** [comment]
Do you have Steam installed in its default path?

**Comment by jazir555** [comment]
I just reverted to the functional implementation, v7 in releases or the current script in main should work

**Comment by RedZombieHD** [comment]
> Do you have Steam installed in its default path?

Yeah I do

**Comment by RedZombieHD** [comment]
Everything is created as normal, but the DelayedExplorerStart.bat doesn't run properly on start up

![PXL_20241228_104616944](https://github.com/user-attachments/assets/b54338b7-b1f1-4f16-b9d3-7474ba32a57b)

**Comment by RedZombieHD** [comment]
Fixed it by adding `rem` to the commented lines and `whoami ^` instead of querying the user

**Comment by RedZombieHD** [comment]
Also it seems from my research `Query User` doesn't work with Home editions of Windows

**Comment by jazir555** [comment]
Swapped query user with whoami, now?

**Comment by RedZombieHD** [comment]
Works perfectly, thank you for all your hard work

**Comment by jazir555** [comment]
No problem!
