### ISSUE TITLE
Could you remove explorer startup sound?

### ISSUE THREAD

**Issue by sharpordie** [jazir555/GamesDows#18]
Your one-click script works amazingly well for my needs with Playnite.

It delayed the windows explorer shell startup.
But it still plays the startup sound after x seconds, is there a way to disable it?

Thanks!

**Comment by jazir555** [comment]
Have you tried disabling Windows system sounds? 

https://gigperformer.com/docs/ultimate-guide-to-optimize-windows-for-stage/turnoffwindowssounds.html

**Comment by jazir555** [comment]
Aside from that there's not much I can do
