### ISSUE TITLE
Computer not saving user info on login screen and when locking the computer

### ISSUE THREAD

**Issue by Emulix** [jazir555/GamesDows#2]
After using the script Disable GamesDows, the computer does not recognize my user anymore.
I have to enter my username at each startup and when locking with Windows + L to access to the desktop.
My computer used to log me in automatically.  Now i cannot  find any solution to revert back to original state.

Edit: I use a local user and not a microsoft account

**Comment by jazir555** [comment]
Is this on the current version of the script in main (Enable GamesDows.bat)?

**Comment by jazir555** [comment]
Ah I misread initially, the Disable script is what's causing that. Interesting. I'll look into it.

**Comment by jazir555** [comment]
https://github.com/jazir555/GamesDows/blob/jazir555-testing/Re-Enable%20Auto-Sign%20In

Can you try downloading this, editing the file to fill in your username and password, then save it and run as admin? I think the issue may have been the disable auto sign in command in the reversion script.

**Comment by Emulix** [comment]
I followed your instruction, but am still facing the issue. Nothing changed.
Something weird is that it's like as if it's asking for a domain.
I am on Windows 11 Family if this helps

**Comment by jazir555** [comment]
I'll have to take a look in the morning

**Comment by jazir555** [comment]
I've updated the script, can you try again?

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Re-Enable%20Auto-Sign%20In.bat

You'll need to edit the file and fill in the username and pass again.

**Comment by jazir555** [comment]
I'm going to close this issue as the commands which caused this have been removed. If you still need help troubleshooting the issue please let me know and I'll continue to troubleshoot with you.

**Comment by jazir555** [comment]
I've created a script which re-enables auto sign in, please download it here and run it as admin:

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Re-Enable%20Auto-Sign%20In.bat
