### ISSUE TITLE
Uninstall script leaves a user

### ISSUE THREAD

**Issue by Watermelon1263** [jazir555/GamesDows#5]
I ran the install script and put my password where it said but the script made a new user that it wouldn't log in so I ran the uninstall script and it left the user

**Comment by jazir555** [comment]
Gotcha, think we've just connected on Reddit. I believe I've identified the issue, and should have a reversion solution for you soon. If possible, what is the name of the created user account?

**Comment by jazir555** [comment]
I've created a script which re-enables auto sign in, please download it here and run it as admin:

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Re-Enable%20Auto-Sign%20In.bat

Closing this as solved.
