### ISSUE TITLE
No startup video

### ISSUE THREAD

**Issue by HetBalderdier** [jazir555/GamesDows#6]
Hello

I've been using your method for a couple of weeks now and it works great, turning my couch PC into a sort of Steam Deck XL

What isn't working though is the Startup Video after the Windows Login Screen: the one that plays when switching from desktop to Big Picture mode or when booting the Steam Deck. It goes straight to the account selection screen.

Is this a code issue or a Steam issue?

**Comment by jazir555** [comment]
> Hello
> 
> I've been using your method for a couple of weeks now and it works great, turning my couch PC into a sort of Steam Deck XL
> 
> What isn't working though is the Startup Video after the Windows Login Screen: the one that plays when switching from desktop to Big Picture mode or when booting the Steam Deck. It goes straight to the account selection screen.

> Is this a code issue or a Steam issue?

Can you clarify what you mean by start up video? Do you mean the big Picture startup animation with the controller? Would it be possible for you to record a video? 

That sounds like it may be one of the startup arguments on line 10:

-nobootstrapupdate -skipinitialbootstrap -skipverifyfiles

You could try removing some, but for me it plays for me with all of those added.

**Comment by jazir555** [comment]
> What isn't working though is the Startup Video after the Windows Login Screen: the one that plays when switching from desktop to Big Picture mode or when booting the Steam Deck. It goes straight to the account selection screen.

Oh rereading your original comment, the video is being suppressed by one of the the steam launch arguments in the script I think, you can try removing them one by one to identify which one is suppressing that if you want to bring that UI element back.
