### ISSUE TITLE
Running Steam as Admin

### ISSUE THREAD

**Issue by PaulDGillis** [jazir555/GamesDows#7]
IDK much about the full security risks in this process. I only plan to use this for the 3 games that require windows/admin, so use at your own risk.
I created a task "SteamShell" in task scheduler to run "Enable GamesDows.bat"'s SteamPath command as admin. Then set the .bat's SteamPath variable to  `C:\Windows\System32\schtasks.exe /run /tn "SteamShell"` Seems to start as it did but now with admin privileges.

**Comment by jazir555** [comment]
Was this in addition to running the full script? If I could get more context that would be helpful. I can script the above, I'm just curious to know if you've made any other modifications or if you just did that on top of the existing script

**Comment by PaulDGillis** [comment]
I replaced the steam command with that schtasks command in the Enable script I downloaded. To create the task manually for testing 3 things are needed:

1. General -> Run with highest privileges
2. Actions -> Start steam.exe -bigpictureui ...
3. Settings -> Uncheck stop task if runs longer than 3 days

It definitely takes a little longer, don't have an exact measurement, but good enough for my use case. It probably can be integrated into script better, saw you already have a task for this. You might know more about working in task scheduler than I do, but I'm happy to help anyway I can

**Comment by jazir555** [comment]
>It definitely takes a little longer, don't have an exact measurement, but good enough for my use case. It probably can be integrated into script better, saw you already have a task for this. You might know more about working in task scheduler than I do, but I'm happy to help anyway I can

Gotcha. This is why I didn't implement starting Steam as admin as a scheduled task, the wait time is a compromise I'd like to avoid. I'm glad this worked for you however! I'm going to keep working on a method to do this with the shell replacement method, because that won't have the same lag attached.

**Comment by jazir555** [comment]
Hmm not sure why I didn't think of this before (derp), but powershell commands can be run directly from a VBS script set as the shell, it doesn't need to have the intermediary step of running a batch script which will reduce the complexity and speed up the process. As far as I can tell this is going to solve the problem once and for all, I'll have to test this on my VM later, but I think this will work quite nicely.

**Comment by PaulDGillis** [comment]
Solve the problem of simplification or admin? Is there a way to elevate steam from the vbs shell script, without triggering the UAC prompt? I'm not familiar with vbs scripting but, could become familiar enough to put a pr together if pointed in the right direction. 

I've got some time and would like to fix an issue with my previous work around. It sometimes fails to start steam about 1/10 times.

**Comment by jazir555** [comment]
> Solve the problem of simplification or admin? Is there a way to elevate steam from the vbs shell script, without triggering the UAC prompt? I'm not familiar with vbs scripting but, could become familiar enough to put a pr together if pointed in the right direction.
> 
> I've got some time and would like to fix an issue with my previous work around. It sometimes fails to start steam about 1/10 times.

I'm sure it would work since the current implementation in my script is the creation of a vbs script which suppresses the window of a second batch script that's created by enablegamesdows.bat. The current VBS script is necessary to suppress the command prompt window from appearing over Steam when explorer starts.

I got the majority of this up by bouncing the code around various AI bots to get it to work, so I'm sure ChatGPT or Claude or whatever can whip something up, I just haven't had time to do yet.

**Comment by jazir555** [comment]
I've created a new version that should launch Steam as Admin which I've thrown on the testing branch, could you give it a shot and let me know if it's working for you?

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Enable%20GamesDows%20v3.bat

**Comment by PaulDGillis** [comment]
> I've created a new version that should launch Steam as Admin which I've thrown on the testing branch, could you give it a shot and let me know if it's working for you?
> 
> https://github.com/jazir555/GamesDows/blob/jazir555-testing/Enable%20GamesDows%20v3.bat
> 
> If you encounter formatting issues when downloading and executing the Enable GamesDows batch script, I'll create a release on the testing branch which should preserve the formatting.

I've pulled v2 from testing, but im currently trying to figure out why steam won't run. The delayed Explorer start task works and there is no errors when running script as admin. Steam doesn't open though sadly

**Comment by jazir555** [comment]
Do you have the Steam startup entry disabled in task manager? If not that would conflict and prevent steam from starting.

**Comment by jazir555** [comment]
If you do have it disabled I probably just need to tweak the power shell command in the new vbscript

**Comment by PaulDGillis** [comment]
I went ahead and tried to run LaunchSteamAsAdmin.vbs  and it complains that the program can't be found at the path. Maybe its the formatting? Because it definitely exists at the right path, and the script saves your scripts to the correct folder.

**Comment by jazir555** [comment]
That sounds like I need to configure it to install visual studio as a
dependency first. Think I had something whipped up for that on testing,
I'll try to see if I can find that.

**Comment by jazir555** [comment]
Can you try running this as admin and then rerun the enable gamesdows script?

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Installvisualstudiobuildtools.bat

**Comment by jazir555** [comment]
> I went ahead and tried to run LaunchSteamAsAdmin.vbs and it complains that the program can't be found at the path. Maybe its the formatting? Because it definitely exists at the right path, and the script saves your scripts to the correct folder.
> 
> Edit: removing launch args it launches just fine. I fixed launch args by moving them to the empty string after the steam.exe path. Now LaunchSteamAsAdmin.vbs works when running manually but still doesn't work when launched from shell

When you say removing launch arguments, do you mean removing the launch arguments when steam is set as the shell? Could use some clarification here

**Comment by PaulDGillis** [comment]
Im not able to run the script yet, will update when I can. I was debugging by running the LaunchSteamAsAdmin.vbs by double clicking it. It couldn't find or run steam until I changed `objShell.ShellExecute "!STEAM_PATH!", "", "", "runas", 1` to `objShell.ShellExecute "!STEAM_PATH!", "!STEAM_ARGS!", "", "runas", 1` but then it runs if I double click it. I had to create the variable myself. It however still wasnt running from the shell

**Comment by jazir555** [comment]
> Im not able to run the script yet, will update when I can. I was debugging by running the LaunchSteamAsAdmin.vbs by double clicking it. It couldn't find or run steam until I changed `objShell.ShellExecute "!STEAM_PATH!", "", "", "runas", 1` to `objShell.ShellExecute "!STEAM_PATH!", "!STEAM_ARGS!", "", "runas", 1` but then it runs if I double click it. I had to create the variable myself. It however still wasnt running from the WinLogon

Hmmm. Could you do me a favor and record a video? I'll see what I can do.

**Comment by PaulDGillis** [comment]
I apologize, I actually un-installed win11 from steamdeck. Windows felt more jank on deck, so I just factory reset it

**Comment by jazir555** [comment]
> I apologize, I actually un-installed win11 from steamdeck. Windows felt more jank on deck, so I just factory reset it. I'll have to try this on future handhelds, as I think I'll get a windows one next time

Sure no worries! Although if you have a VM this will still work on the VM, so if you have time that would really help with troubleshooting if you wouldn't mind going through the process again.

**Comment by jazir555** [comment]
Update: This has now been implemented in V3!
