### ISSUE TITLE
V2 for steam does not work.

### ISSUE THREAD

**Issue by Staghelm715** [jazir555/GamesDows#8]
It's briefly shows admin login, then I get a black screen with the windows loading sound and it takes a few minutes to even start steam afterwards. If there is any other info you would like me to provide, just ask.

Also, I thought I would use this to ask a question. Would it be possible to add css loader to load with steam big picture on startup?

**Comment by jazir555** [comment]
>It's briefly shows admin login, then I get a black screen with the windows loading sound and it takes a few minutes to even start steam afterwards. If there is any other info you would like me to provide, just ask.

A video would be great if you wouldn't mind!

>Would it be possible to add css loader to load with steam big picture on startup?

I'd need more info on how CSS loader works, can you link me to some documentation? I'd need to know what I need to do to get it to start up, I have no experience with CSS loader on Windows. If it's something super simple like launch arguments that's easy.

**Comment by cdekort** [comment]
Also having difficulties getting up and running. Steam doesn't launch, neither on a background process. Would love to get this going.

**Comment by jazir555** [comment]
@cdekort 

This is definitely a V2 bug. If you try V1 out (Steam Variant), it'll work. I don't have a Playnite V1 variant, but I can make one. V2 uses a VBScript set as the shell which I was unsure was viable, seems like I'll have to find an alternative workaround to get Steam to start as admin. 

Playnite actually shouldn't need to start as admin, so making a V1 variant for Playnite should be sufficient. I'll maybe try to work on that tonight or tomorrow. It's really just swapping paths in the bat file, so I should be able to knock it out quickly when I get to it.

**Comment by jazir555** [comment]
> Also having difficulties getting up and running. Steam doesn't launch, neither on a background process. Would love to get this going.

Actually question, did you disable the Steam autostart entry in task manager yet?

**Comment by Staghelm715** [comment]
> >It's briefly shows admin login, then I get a black screen with the windows loading sound and it takes a few minutes to even start steam afterwards. If there is any other info you would like me to provide, just ask.
> 
> 
> 
> A video would be great if you wouldn't mind!
> 
> here is the video: https://github.com/user-attachments/assets/8b553c8c-aa24-49e8-9a5c-21d2c2d95905

> it's black for a about 20 seconds before the acus logo and I cut about 12 secs before the files popped up for some reason. It then just sits there and does not open steam. 
 
> >Would it be possible to add css loader to load with steam big picture on startup?
> 
> 
>
> I'd need more info on how CSS loader works, can you link me to some documentation? I'd need to know what I need to do to get it to start up, I have no experience with CSS loader on Windows. If it's something super simple like launch arguments that's easy, otherwise I'd have to look into it.
> 
> 
> here is a link to css loader: https://deckthemes.com/ and https://github.com/DeckThemes/SDH-CssLoader

> Edit: Also from what you wrote it sounds like Steam is still starting up automatically, just really slowly?

From what I thought. This time during the video it did nothing. I have a decent computer and I am running the os on an ssd, so it is never that slow.

**Comment by jazir555** [comment]
From what I see in your video that is expected behavior when Steam fails to launch. Explorer.exe is still starting in the background with the delay timer when run via the scheduled task, Steam just isn't opening when you're logged in automatically. V1 will fix that and start Steam correctly (not as admin though).

**Comment by Staghelm715** [comment]
> From what I see in your video that is expected behavior when Steam fails to launch. Explorer.exe is still starting in the background with the delay timer when run via the scheduled task, Steam just isn't opening when you're logged in automatically. V1 will fix that and start Steam correctly (not as admin though).

Yes. I have reverted back to V1 and it is working just fine like it always has. Thank you for your reply!

**Comment by jazir555** [comment]
> > From what I see in your video that is expected behavior when Steam fails to launch. Explorer.exe is still starting in the background with the delay timer when run via the scheduled task, Steam just isn't opening when you're logged in automatically. V1 will fix that and start Steam correctly (not as admin though).
> 
> Yes. I have reverted back to V1 and it is working just fine like it always has. Thank you for your reply!

Great to hear that reverting went fine. I'll try some new things to get V2 into a working state!

**Comment by cdekort** [comment]
> > Also having difficulties getting up and running. Steam doesn't launch, neither on a background process. Would love to get this going.
> 
> Actually question, did you disable the Steam autostart entry in task manager yet?

Yes, It's disabled.

**Comment by jazir555** [comment]
> > > Also having difficulties getting up and running. Steam doesn't launch, neither on a background process. Would love to get this going.
> > 
> > 
> > Actually question, did you disable the Steam autostart entry in task manager yet?
> 
> Yes, It's disabled.

It's an issue with V2. Is V1 working for you?

**Comment by cdekort** [comment]
V2 now works perfectly fine for me! I just had to set the password for login in the script as you described in the reddit post. Maybe at that instruction to the read me as well?
-------- Original Message --------On 9/1/24 11:32 AM, jazir5  wrote:



Also having difficulties getting up and running. Steam doesn't launch, neither on a background process. Would love to get this going.

Actually question, did you disable the Steam autostart entry in task manager yet?

Yes, It's disabled.

It's an issue with V2. Is V1 working for you?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jazir555/GamesDows/issues/8#issuecomment-2323276630",
"url": "https://github.com/jazir555/GamesDows/issues/8#issuecomment-2323276630",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jazir555** [comment]
> V2 now works perfectly fine for me! I just had to set the password for login in the script as you described in the reddit post. Maybe add that instruction to the read me as well?

To confirm, V2 is working correctly for you?

**Comment by cdekort** [comment]
Yes perfectly, however I can't exit steam back to desktop, nor remove the script using the uninstall script. It doesn't run when I try to.

> > V2 now works perfectly fine for me! I just had to set the password for login in the script as you described in the reddit post. Maybe add that instruction to the read me as well?
> 
> To confirm, V2 is working correctly for you? Not just V1?

**Comment by jazir555** [comment]
> Yes perfectly, however I can't exit steam back to desktop, nor remove the script using the uninstall script. It doesn't run when I try to.
> 
> > > V2 now works perfectly fine for me! I just had to set the password for login in the script as you described in the reddit post. Maybe add that instruction to the read me as well?
> > 
> > 
> > To confirm, V2 is working correctly for you? Not just V1?

> > To confirm, V2 is working correctly for you? Not just V1?

So explorer.exe isn't starting in the background for you?

**Comment by cdekort** [comment]
No, I'm on windows 11

**Comment by jazir555** [comment]
> No, I'm on windows 11

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Enable%20GamesDows%20v2.bat

Could you give this version a shot? When I went back to look at V2 I realized that I changed the background explorer launch method, I reverted it to the V1 method.

**Comment by cdekort** [comment]
I will try, I couldn't run the uninstall script so curious if I can run this to overwrite the current configuration. Any specific method of getting out of this stuck place of not being able to execute script from the file to explorer? Like I can get there, but they don't seem to execute.

**Comment by jazir555** [comment]
>I will try, I couldn't run the uninstall script so curious if I can run this to overwrite the current configuration. 

Yes it will overwrite the current configuration. What do you mean by they don't execute?

**Comment by jazir555** [comment]
> I will try, I couldn't run the uninstall script so curious if I can run this to overwrite the current configuration. Any specific method of getting out of this stuck place of not being able to execute script from the file to explorer? Like I can get there, but they don't seem to execute.

Are you able to right click on the script in an explorer window and run it as admin? If so, what happens when you try to run the script?

**Comment by cdekort** [comment]
Last time I tried to run the uninstall with admin, it didn't execute indeed. I will see if I can overwrite it tomorrow using your new script.

> > I will try, I couldn't run the uninstall script so curious if I can run this to overwrite the current configuration. Any specific method of getting out of this stuck place of not being able to execute script from the file to explorer? Like I can get there, but they don't seem to execute.
> 
> Are you able to right click on the script in an explorer window and run it as admin? If so, what happens when you try to run the script?

**Comment by jazir555** [comment]
> Last time I tried to run the uninstall with admin, it didn't execute indeed. I will see if I can overwrite it tomorrow using your new script.
> 
> > > I will try, I couldn't run the uninstall script so curious if I can run this to overwrite the current configuration. Any specific method of getting out of this stuck place of not being able to execute script from the file to explorer? Like I can get there, but they don't seem to execute.
> > 
> > 
> > Are you able to right click on the script in an explorer window and run it as admin? If so, what happens when you try to run the script?

When you say didn't execute, do you mean no CMD window appeared where you could see commands running? If explorer isn't starting automatically for you, are you launching it via task manager by starting explorer.exe as a new task? You first need to reset the shell to explorer.exe before launching it. Otherwise you have to start it twice I believe. That's the correct method to get explorer running.
